### ISSUE TITLE
Constrain who can delete a folder and contents (2J)

### ISSUE THREAD

**Issue by MartinFoys** [performant-software/dm-2#204]
Anybody can delete a folder of content - can this be constrained to admins and the creator of the folder?

**Comment by blms** [comment]
It seems this is already constrained, such that the only people who can delete a folder are:
- Site admins
- Project creators
- Collaborators with "Write" or "Admin" access

Currently, collaborators with "Read" access, and the general public, cannot delete folders.

Should it be further constrained so that collaborators with "Write" access should also not be able to delete folders?

**Comment by MartinFoys** [comment]
Ben - yep it'd be great to constrain it to admin collaborators only. One big issue here is the resource being used by student writer-collaborators, where students have accidentally deleted other student's folders of work!

**Comment by blms** [comment]
I see, thanks Martin! That makes a lot of sense.

**Comment by blms** [comment]
Closed by #309.
